// Advent of Code - Day 7

import { describe, expect, test } from 'vitest';
import { part1 } from '../part1.js';
import { part2 } from '../part2.js';

const input = `.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`;

describe('Day 7', () => {
  test('Part 1', () => {
    expect(part1(input)).toBe(21);
  });

  test('Part 2', () => {
    expect(part2(input)).toBe(40);
  });
});
